# Generated by Django 3.2.5 on 2023-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='fecha_desde_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Desde Vigencia'),
        ),
        migrations.AddField(
            model_name='publication',
            name='fecha_hasta_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Hasta Vigencia'),
        ),
        migrations.AddField(
            model_name='publication',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
            preserve_default=False,
        ),
    ]
