# Generated by Django 3.2.5 on 2023-10-25 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_extended_user_inactive_until'),
        ('vehicles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_create_user', to='users.extended_user'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='modification_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_modification_user', to='users.extended_user'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tarjeton',
            field=models.ImageField(null=True, upload_to='tarjeton/', verbose_name='tarjeton'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tarjeton_date',
            field=models.DateField(null=True),
        ),
    ]
