# Generated by Django 3.2.5 on 2023-08-29 23:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('states', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('activation_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=6, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('used', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cell_phone', models.CharField(default='', max_length=10, null=True)),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                # ('expiration_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                # ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extended_User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended_user', serialize=False, to='auth.user')),
                ('document_number', models.CharField(max_length=20, null=True)),
                ('date_birth', models.DateField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='users/', verbose_name='photo')),
                ('cell_phone', models.CharField(default='', max_length=10, null=True)),
                ('phone_secondary', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('description_address', models.TextField(default='', null=True)),
                ('favorite_station', models.CharField(max_length=50, null=True)),
                ('favorite_music', models.CharField(max_length=50, null=True)),
                ('contact_person_name', models.CharField(max_length=150, null=True)),
                ('contact_person_phone', models.CharField(max_length=10, null=True)),
                ('call', models.BooleanField(default=False)),
                # ('inactive_until', models.DateTimeField(null=True)),
                # ('contact_text_check', models.BooleanField(default=False)),
                # ('contact_experience_check', models.BooleanField(default=False)),
                # ('exchange_data_check', models.BooleanField(default=False)),
                ('authorizing_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorizing_user', to=settings.AUTH_USER_MODEL)),
                ('blood_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.blood_types')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.city')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
            ],
        ),
        migrations.CreateModel(
            name='ValidationCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0, null=True)),
                # ('bonus_direct', models.BigIntegerField(default=0)),
                # ('bonus_indirect', models.BigIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state')),
                ('type_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.typesubscription')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('payment_method', models.CharField(max_length=30, null=True)),
                ('id_transaction', models.CharField(max_length=30, null=True)),
                ('payment_reference', models.CharField(max_length=50, null=True, unique=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.coupon')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.invoicestate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.extended_user')),
            ],
        ),
        migrations.AddField(
            model_name='extended_user',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.gender'),
        ),
        migrations.AddField(
            model_name='extended_user',
            name='inviting_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviting_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extended_user',
            name='state',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscription'),
        ),
        migrations.CreateModel(
            name='CardSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payday', models.DateField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.card')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.invoice')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.extended_user'),
        ),
        migrations.AddField(
            model_name='card',
            name='validation_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.validationcard'),
        ),
        # SE PASA AL 0002 por migracion de SQL
        # migrations.CreateModel(
        #     name='AllyCategory',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=200)),
        #         ('create_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
        #         ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllyCategory_create_user', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Ally',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('photo_local_1', models.ImageField(upload_to='ally/', verbose_name='photo_local_1')),
        #         ('photo_local_2', models.ImageField(blank=True, null=True, upload_to='ally/', verbose_name='photo_local_2')),
        #         ('photo_local_3', models.ImageField(blank=True, null=True, upload_to='ally/', verbose_name='photo_local_3')),
        #         ('name', models.CharField(max_length=200)),
        #         ('description', models.TextField()),
        #         ('number_mercantil', models.CharField(max_length=100)),
        #         ('cell_phone', models.CharField(default='', max_length=10, null=True)),
        #         ('address', models.CharField(default='', max_length=100, null=True)),
        #         ('inactive_until', models.DateTimeField(blank=True, null=True)),
        #         ('description_state', models.TextField(blank=True)),
        #         ('create_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
        #         ('modification_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
        #         ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.allycategory')),
        #         ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.city')),
        #         ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ally_create_user', to='users.extended_user')),
        #         ('modification_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ally_modification_user', to='users.extended_user')),
        #         ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state')),
        #         ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ally_user', to='users.extended_user')),
        #     ],
        # ),
    ]
