# Generated by Django 3.2.5 on 2023-08-29 23:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllyCategory_create_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_local_1', models.ImageField(upload_to='ally/', verbose_name='photo_local_1')),
                ('photo_local_2', models.ImageField(blank=True, null=True, upload_to='ally/', verbose_name='photo_local_2')),
                ('photo_local_3', models.ImageField(blank=True, null=True, upload_to='ally/', verbose_name='photo_local_3')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number_mercantil', models.CharField(max_length=100)),
                ('cell_phone', models.CharField(default='', max_length=10, null=True)),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('inactive_until', models.DateTimeField(blank=True, null=True)),
                ('description_state', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.allycategory')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.city')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ally_create_user', to='users.extended_user')),
                ('modification_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ally_modification_user', to='users.extended_user')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ally_user', to='users.extended_user')),
            ],
        ),
        migrations.AddField(
            model_name='Extended_User',
            name='inactive_until',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='Extended_User',
            name='contact_text_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='Extended_User',
            name='contact_experience_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='Extended_User',
            name='exchange_data_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='Subscription',
            name='bonus_direct',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='Subscription',
            name='bonus_indirect',
            field=models.BigIntegerField(default=0),
        ),
        
    ]
