# Generated by Django 3.2.5 on 2023-10-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended_user',
            name='inactive_until',
            field=models.DateTimeField(null=True),
        ),
    ]
