# Generated by Django 3.2.5 on 2023-08-29 23:36
from django.contrib.auth.models import *
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_extended_user_inactive_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='Coupon',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.city'),
        ),
        migrations.AddField(
            model_name='Coupon',
            name='expiration_date',
            field=models.DateTimeField(blank=True,null=True, default=timezone.now),
        ),
    ]
